export class Country{
  constructor(
    public code:string,
    public name: string
    ){}
}
export const ListOfCountries:Country[] =[
  new Country("AF","Afganistan"),
  new Country("AL","Albania"),
  new Country("DZ","Algieria"),
  new Country("AD","Andora"),
  new Country("AO","Angola"),
  new Country("AI","Anguilla"),
  new Country("AG","Antigua i Barbuda"),
  new Country("SA","Arabia Saudyjska"),
  new Country("AR","Argentyna"),
  new Country("AM","Armenia"),
  new Country("AW","Aruba"),
  new Country("AU","Australia"),
  new Country("AT","Austria"),
  new Country("AZ","Azerbejdżan"),
  new Country("BS","Bahamy"),
  new Country("BH","Bahrajn"),
  new Country("BD","Bangladesz"),
  new Country("BB","Barbados"),
  new Country("BE","Belgia"),
  new Country("BZ","Belize"),
  new Country("BJ","Benin"),
  new Country("BM","Bermudy"),
  new Country("BT","Bhutan"),
  new Country("BY","Białoruś"),
  new Country("BO","Boliwia"),
  new Country("BA","Bośnia i Hercegowina"),
  new Country("BW","Botswana"),
  new Country("BR","Brazylia"),
  new Country("BN","Brunei"),
  new Country("IO","Brytyjskie Terytorium Oceanu Indyjskiego"),
  new Country("VG","Brytyjskie Wyspy Dziewicze"),
  new Country("BG","Bułgaria"),
  new Country("BF","Burkina Faso"),
  new Country("BI","Burundi"),
  new Country("CL","Chile"),
  new Country("CN","Chiny"),
  new Country("HR","Chorwacja"),
  new Country("CI","Côte d’Ivoire"),
  new Country("AN","Curaçao"),
  new Country("CW","Curaçao"),
  new Country("CY","Cypr"),
  new Country("TD","Czad"),
  new Country("ME","Czarnogóra"),
  new Country("CZ","Czechy"),
  new Country("DK","Dania"),
  new Country("CD","Demokratyczna Republika Konga"),
  new Country("DM","Dominika"),
  new Country("DO","Dominikana"),
  new Country("DJ","Dżibuti"),
  new Country("EG","Egipt"),
  new Country("EC","Ekwador"),
  new Country("ER","Erytrea"),
  new Country("EE","Estonia"),
  new Country("SZ","Eswatini"),
  new Country("ET","Etiopia"),
  new Country("FK","Falklandy"),
  new Country("FJ","Fidżi"),
  new Country("PH","Filipiny"),
  new Country("FI","Finlandia"),
  new Country("FR","Francja"),
  new Country("TF","Francuskie Terytoria Południowe i Antarktyczne"),
  new Country("GA","Gabon"),
  new Country("GM","Gambia"),
  new Country("GS","Georgia Południowa i Sandwich Południowy"),
  new Country("GH","Ghana"),
  new Country("GI","Gibraltar"),
  new Country("GR","Grecja"),
  new Country("GD","Grenada"),
  new Country("GL","Grenlandia"),
  new Country("GE","Gruzja"),
  new Country("GU","Guam"),
  new Country("GG","Guernsey"),
  new Country("GY","Gujana"),
  new Country("GF","Gujana Francuska"),
  new Country("GP","Gwadelupa"),
  new Country("GT","Gwatemala"),
  new Country("GN","Gwinea"),
  new Country("GW","Gwinea Bissau"),
  new Country("GQ","Gwinea Równikowa"),
  new Country("HT","Haiti"),
  new Country("ES","Hiszpania"),
  new Country("NL","Holandia"),
  new Country("HN","Honduras"),
  new Country("IN","Indie"),
  new Country("ID","Indonezja"),
  new Country("IQ","Irak"),
  new Country("IR","Iran"),
  new Country("IE","Irlandia"),
  new Country("IS","Islandia"),
  new Country("IL","Izrael"),
  new Country("JM","Jamajka"),
  new Country("JP","Japonia"),
  new Country("YE","Jemen"),
  new Country("JE","Jersey"),
  new Country("JO","Jordania"),
  new Country("KY","Kajmany"),
  new Country("KH","Kambodża"),
  new Country("CM","Kamerun"),
  new Country("CA","Kanada"),
  new Country("QA","Katar"),
  new Country("KZ","Kazachstan"),
  new Country("KE","Kenia"),
  new Country("KG","Kirgistan"),
  new Country("KI","Kiribati"),
  new Country("CO","Kolumbia"),
  new Country("KM","Komory"),
  new Country("CG","Kongo"),
  new Country("KR","Korea Południowa"),
  new Country("KP","Korea Północna"),
  new Country("CR","Kostaryka"),
  new Country("CU","Kuba"),
  new Country("KW","Kuwejt"),
  new Country("LA","Laos"),
  new Country("LS","Lesotho"),
  new Country("LB","Liban"),
  new Country("LR","Liberia"),
  new Country("LY","Libia"),
  new Country("LI","Liechtenstein"),
  new Country("LT","Litwa"),
  new Country("LU","Luksemburg"),
  new Country("LV","Łotwa"),
  new Country("MK","Macedonia Północna"),
  new Country("MG","Madagaskar"),
  new Country("YT","Majotta"),
  new Country("MW","Malawi"),
  new Country("MV","Malediwy"),
  new Country("MY","Malezja"),
  new Country("ML","Mali"),
  new Country("MT","Malta"),
  new Country("MP","Mariany Północne"),
  new Country("MA","Maroko"),
  new Country("MQ","Martynika"),
  new Country("MR","Mauretania"),
  new Country("MU","Mauritius"),
  new Country("MX","Meksyk"),
  new Country("FM","Mikronezja"),
  new Country("MM","Mjanma (Birma)"),
  new Country("MD","Mołdawia"),
  new Country("MC","Monako"),
  new Country("MN","Mongolia"),
  new Country("MS","Montserrat"),
  new Country("MZ","Mozambik"),
  new Country("NA","Namibia"),
  new Country("NR","Nauru"),
  new Country("NP","Nepal"),
  new Country("BQ","Niderlandy Karaibskie"),
  new Country("DE","Niemcy"),
  new Country("NE","Niger"),
  new Country("NG","Nigeria"),
  new Country("NI","Nikaragua"),
  new Country("NU","Niue"),
  new Country("NF","Norfolk"),
  new Country("NO","Norwegia"),
  new Country("NC","Nowa Kaledonia"),
  new Country("NZ","Nowa Zelandia"),
  new Country("OM","Oman"),
  new Country("PK","Pakistan"),
  new Country("PW","Palau"),
  new Country("PA","Panama"),
  new Country("PG","Papua-Nowa Gwinea"),
  new Country("PY","Paragwaj"),
  new Country("PE","Peru"),
  new Country("PN","Pitcairn"),
  new Country("PF","Polinezja Francuska"),
  new Country("PL","Polska"),
  new Country("PR","Portoryko"),
  new Country("PT","Portugalia"),
  new Country("ZA","Republika Południowej Afryki"),
  new Country("CF","Republika Środkowoafrykańska"),
  new Country("CV","Republika Zielonego Przylądka"),
  new Country("RE","Reunion"),
  new Country("RU","Rosja"),
  new Country("RO","Rumunia"),
  new Country("RW","Rwanda"),
  new Country("EH","Sahara Zachodnia"),
  new Country("KN","Saint Kitts i Nevis"),
  new Country("LC","Saint Lucia"),
  new Country("VC","Saint Vincent i Grenadyny"),
  new Country("BL","Saint-Barthélemy"),
  new Country("MF","Saint-Martin"),
  new Country("PM","Saint-Pierre i Miquelon"),
  new Country("SV","Salwador"),
  new Country("WS","Samoa"),
  new Country("AS","Samoa Amerykańskie"),
  new Country("SM","San Marino"),
  new Country("SN","Senegal"),
  new Country("RS","Serbia"),
  new Country("SC","Seszele"),
  new Country("SL","Sierra Leone"),
  new Country("SG","Singapur"),
  new Country("SX","Sint Maarten"),
  new Country("SK","Słowacja"),
  new Country("SI","Słowenia"),
  new Country("SO","Somalia"),
  new Country("HK","SRA Hongkong (Chiny)"),
  new Country("MO","SRA Makau (Chiny)"),
  new Country("LK","Sri Lanka"),
  new Country("US","Stany Zjednoczone"),
  new Country("SD","Sudan"),
  new Country("SS","Sudan Południowy"),
  new Country("SR","Surinam"),
  new Country("SJ","Svalbard i Jan Mayen"),
  new Country("SY","Syria"),
  new Country("CH","Szwajcaria"),
  new Country("SE","Szwecja"),
  new Country("TJ","Tadżykistan"),
  new Country("TH","Tajlandia"),
  new Country("TW","Tajwan"),
  new Country("TZ","Tanzania"),
  new Country("TL","Timor Wschodni"),
  new Country("TG","Togo"),
  new Country("TK","Tokelau"),
  new Country("TO","Tonga"),
  new Country("TT","Trynidad i Tobago"),
  new Country("TN","Tunezja"),
  new Country("TR","Turcja"),
  new Country("TM","Turkmenistan"),
  new Country("TC","Turks i Caicos"),
  new Country("TV","Tuvalu"),
  new Country("UG","Uganda"),
  new Country("UA","Ukraina"),
  new Country("UY","Urugwaj"),
  new Country("UZ","Uzbekistan"),
  new Country("VU","Vanuatu"),
  new Country("WF","Wallis i Futuna"),
  new Country("VA","Watykan"),
  new Country("VE","Wenezuela"),
  new Country("HU","Węgry"),
  new Country("GB","Wielka Brytania"),
  new Country("VN","Wietnam"),
  new Country("IT","Włochy"),
  new Country("BV","Wyspa Bouveta"),
  new Country("CX","Wyspa Bożego Narodzenia"),
  new Country("IM","Wyspa Man"),
  new Country("SH","Wyspa Świętej Heleny"),
  new Country("AX","Wyspy Alandzkie"),
  new Country("CK","Wyspy Cooka"),
  new Country("VI","Wyspy Dziewicze Stanów Zjednoczonych"),
  new Country("CC","Wyspy Kokosowe"),
  new Country("MH","Wyspy Marshalla"),
  new Country("FO","Wyspy Owcze"),
  new Country("SB","Wyspy Salomona"),
  new Country("ST","Wyspy Świętego Tomasza i Książęca"),
  new Country("ZM","Zambia"),
  new Country("ZW","Zimbabwe"),
  new Country("AE","Zjednoczone Emiraty Arabskie")
]
